version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: video_sharing_app
    container_name: app
    entrypoint: ./docker-entrypoint.sh
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - bundle:/bundle
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: 45532580144c978849782aa87acb07bf # It should be share internal
      DB_HOST: postgres
      DB_PASSWORD: 123456a@
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456a@
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6.0.5-alpine
    container_name: redis
    tty: true
    ports:
      - '6380:6379'
  app_test:
    image: video_sharing_app
    container_name: app_test
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - bundle:/bundle
    environment:
      RAILS_ENV: test
volumes:
  bundle:
  db_data:
